server:
  port: 4000
  servlet:
    encoding:
      charset: utf-8

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/MMS_valley_ball?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: postgres
    password: 1111

  sql:
    init:
      mode: never

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate
    properties:
      format_sql: true
      show-sql: true

  jwt:
    secret: ${SECRET}

  mail:
    host: smtp.gmail.com           # 이메일 서버 호스트 (예: Gmail의 SMTP 서버)
    port: 587                      # SMTP 서버 포트
    username: ${mail.username}     # 발신자 이메일 주소
    password: ${mail.password}     # 발신자 이메일의 비밀번호
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true